
name: Build ZIP file

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Get version
        run: |
          OSVER=`cat version.txt`
          echo "OSVER=$OSVER" >> $GITHUB_ENV
          echo The current version is $OSVER!

      - name: ZIP files
        run: zip "3DFox_OS_EUR_$OSVER.zip" ./ -r
        if: ${{ github.ref_name == 'main' }}

      - name: Upload ZIP file as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: 3DFox OS
          path: ./3DFox_OS_EUR_${{ env.OSVER }}.zip
        if: ${{ github.ref_name == 'main' }}
