
name: Build ZIP file

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 2'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Get version
        run: |
          OSVER=`cat version.txt`
          echo "OSVER=$OSVER" >> $GITHUB_ENV
          echo The current version is $OSVER!

      - name: ZIP files for stable release
        run: zip "3DFox_OS_EUR_$OSVER.zip" ./ -r
        if: (github.ref_name == 'main' && github.event_name == 'push')

      - name: Upload stable ZIP file as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: 3DFox OS
          path: ./3DFox_OS_EUR_${{ env.OSVER }}.zip
        if: (github.ref_name == 'main' && github.event_name == 'push')
        
      - name: ZIP files for nightly release
        run: zip "3DFox_OS_EUR_nightly.zip" ./ -r
        if: |
          ${{ github.ref_name == 'dev' }} ||
          ${{ github.event_name == 'pull_request' }} ||
          ${{ github.event_name == 'schedule' }}

      - name: Upload nightly ZIP file as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: 3DFox OS
          path: ./3DFox_OS_EUR_nightly.zip
        if: |
          ${{ github.ref_name == 'dev' }} ||
          ${{ github.event_name == 'pull_request' }} ||
          ${{ github.event_name == 'schedule' }}

      - name: Make short version tag
        run: |
          SHORT_OSVER="$OSVER"
          SHORT_OSVER=`sed 's/[v]*//' <<< "$SHORT_OSVER"`
          echo "SHORT_OSVER=$SHORT_OSVER" >> $GITHUB_ENV
        if: (github.ref_name == 'main' && github.event_name == 'push')
        
      - name: Create a release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "3DFox_OS_EUR_${{ env.OSVER }}.zip"
          generateReleaseNotes: true
          name: "!!!3DFox OS ${{ env.SHORT_OSVER }}!!!"
          tag: "${{ env.OSVER }}"
          draft: true
          makeLatest: true
          skipIfReleaseExists: true
          allowUpdates: true
          updateOnlyUnreleased: true
        if: (github.ref_name == 'main' && github.event_name == 'push')
